src/Entity/Crypto.php
<?php

namespace App\Entity;

use App\Repository\CryptoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CryptoRepository::class)]
class Crypto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $logo_url;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 30)]
    private $symbol;

    #[ORM\Column(type: 'float', nullable: true)]
    private $price;

    #[ORM\Column(type: 'integer')]
    private $ranking;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'cryptos')]
    private $user;

    #[ORM\ManyToMany(targetEntity: Wallet::class, mappedBy: 'relation')]
    private $userWallet;

    #[ORM\ManyToMany(targetEntity: Wallet::class, mappedBy: 'Crypto_in_wallet')]
    private $wallets;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->userWallet = new ArrayCollection();
        $this->wallets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logo_url;
    }

    public function setLogoUrl(?string $logo_url): self
    {
        $this->logo_url = $logo_url;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    public function setSymbol(string $symbol): self
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getRanking(): ?int
    {
        return $this->ranking;
    }

    public function setRanking(int $ranking): self
    {
        $this->ranking = $ranking;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Wallet>
     */
    public function getWallets(): Collection
    {
        return $this->wallets;
    }

    public function addWallet(Wallet $wallet): self
    {
        if (!$this->wallets->contains($wallet)) {
            $this->wallets[] = $wallet;
            $wallet->addCryptoInWallet($this);
        }

        return $this;
    }

    public function removeWallet(Wallet $wallet): self
    {
        if ($this->wallets->removeElement($wallet)) {
            $wallet->removeCryptoInWallet($this);
        }

        return $this;
    }

}

src/Controller/CryptoController.php
<?php

namespace App\Controller;

use App\Entity\Crypto;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CryptoController extends AbstractController
{
    #[Route('/', name: 'app_crypto')]
    public function index(EntityManagerInterface $doctrine): Response
    {

        $repo = $doctrine->getRepository(Crypto::class);
        $cryptos = $repo->findAll();

        return $this->render('crypto/cryptoList.html.twig', [ 'cryptos' => $cryptos ]);
    }

    #[Route('add-url/crypto', name: 'add_url_crypto')]
    public function addUrl(EntityManagerInterface $doctrine): Response
    {

        $crypto = new Crypto();
        $crypto->setName('Oasis Network');
        $crypto->setLogoUrl('https://dynamic-assets.coinbase.com/f0e7bb761f5b88eb3b89da4d170d32cc5b961714e883868fa735115406457dbd9ddc7deed8428dffce01bf48dc656e24f64fd1c5489551748ef3917dc5ba70ad/asset_icons/bfaeca758204617fd9159f15de134f66e922a538b913d8d781bef4d98a25cec4.png');
        $crypto->setDescription('Oasis es una cadena de bloques de capa base, como Ethereum o Bitcoin , pero está construida desde cero, con confidencialidad de datos y ganancias de rendimiento de hasta 1,000 transacciones por segundo.');
        $crypto->setSymbol('ROSE');
        $crypto->setPrice(0.19352543 );
        $crypto->setRanking(6);

        $doctrine->persist($crypto);
        $doctrine->flush();

        return $this->json([
            'message' => 'Crypto Added To the DB!',
            'path' => 'src/Controller/CryptoController.php',
        ]);
    }
    #[Route('search/crypto/{id}', name: 'search_crypto')]
    public function searchCrypto(EntityManagerInterface $doctrine, $id): Response
    {

        $repo = $doctrine->getRepository(Crypto::class);
        $crypto = $repo->find($id);

        return $this->render('crypto/cryptoSearch.html.twig', [ 'crypto' => $crypto ]);
    }
}

templates/crypto/cryptoList.html.twig
{% extends 'base.html.twig' %}

    {% block body %}

        {% for message in app.flashes('success') %}
            <div class=" alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ message }}
            </div>
        {% endfor %}

        <h2 style="text-align: center; font-size: 50px; margin: 70px 0 30px 0; color: #969595; font-weight: 700; " class="animate__animated animate__fadeInDown">Crypto List</h2>

                <div class="flex__container flex-row">
                    {% for item in cryptos %}

                        <div class="flex__box">
                            <div class="flex__item animate__animated animate__fadeIn">
                                <a href="{{path('search_crypto', {'id': item.id})}}"><img src="{{item.logoUrl}}" class="flex__img"> </a>
                                <h2> {{item.name}}</h2><span style="color:#949494; font-weight:200; font-size:13px;"> ({{item.symbol}}) </span>
                                <h2 style="color:#656565; font-weight: 400; font-size:20px"> {{item.price}}€ </h2>
                                <a class="btn btn-primary" href="{{path('search_crypto', {'id': item.id})}}">+ Info </a>
                            </div>
                         </div>

                    {% endfor %}



                </div>

    {% endblock %}

templates/crypto/cryptoSearch.html.twig
{% extends 'base.html.twig' %}

    {% block body %}

        {% if crypto %}
            <div class="item-detail__box">
                <img class="item__img" src="{{ crypto.logoUrl }}" alt="{{ crypto.name }}">

                <div class="item-detail__text">
                    <h1 class="item__title"><span
                                style="color:#c9c7c7; padding-right: 5px">#{{ crypto.ranking }}</span> {{ crypto.name }}
                        <span class="item__symbol">  ({{ crypto.symbol }}) </span></h1>
                    <h2 class="item__price">  {{ crypto.price }} € </h2>
                    <p class="item__desc">{{ crypto.description }}</p>
                    {% if is_granted("ROLE_USER") %}
                        <a class="btn btn-primary"
                           href="{{ path('add_crypto_wallet', { 'idUser':app.user.id, 'idCrypto': crypto.id}) }}">
                            Añadir a Cartera </a>
                    {% endif %}

                </div>
            </div>
        {% endif %}
        {% if not crypto %}
            <div class="item-detail__404">
                <h1 class="item__title"> This crypto is not in the Database </h1>
                <img style="width:100wh; height: auto" src="/img/404.jpeg" alt="not-found">
            </div>
        {% endif %}



        <script>
            // Get all elements with class="closebtn"
            var close = document.getElementsByClassName("closebtn");
            var i;

            // Loop through all close buttons
            for (i = 0; i < close.length; i++) {
                // When someone clicks on a close button
                close[i].onclick = function () {

                    // Get the parent of <span class="closebtn"> (<div class="alert">)
                    var div = this.parentElement;

                    // Set the opacity of div to 0 (transparent)
                    div.style.opacity = "0";

                    // Hide the div after 600ms (the same amount of milliseconds it takes to fade out)
                    setTimeout(function () {
                        div.style.display = "none";
                    }, 600);
                }
            }
        </script>

    {% endblock %}